//
// Generated file, do not edit! Created by opp_msgtool 6.1 from inet/routing/fsr/FSR.msg.
//

#ifndef __INET_FSR_M_H
#define __INET_FSR_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class FSRControlPacket;
struct FSRRoute;
class FSRUpdatePacket;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Enum generated from <tt>inet/routing/fsr/FSR.msg:9</tt> by opp_msgtool.
 * <pre>
 * enum FSRControlPacketType
 * {
 *     UPDATE = 1;
 * }
 * </pre>
 */
enum FSRControlPacketType {
    UPDATE = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FSRControlPacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FSRControlPacketType& e) { int n; b->unpack(n); e = static_cast<FSRControlPacketType>(n); }

/**
 * Class generated from <tt>inet/routing/fsr/FSR.msg:14</tt> by opp_msgtool.
 * <pre>
 * class FSRControlPacket extends FieldsChunk
 * {
 *     FSRControlPacketType packetType = static_cast<FSRControlPacketType>(-1);
 * }
 * </pre>
 */
class INET_API FSRControlPacket : public ::inet::FieldsChunk
{
  protected:
    FSRControlPacketType packetType = static_cast<FSRControlPacketType>(-1);

  private:
    void copy(const FSRControlPacket& other);

  protected:
    bool operator==(const FSRControlPacket&) = delete;

  public:
    FSRControlPacket();
    FSRControlPacket(const FSRControlPacket& other);
    virtual ~FSRControlPacket();
    FSRControlPacket& operator=(const FSRControlPacket& other);
    virtual FSRControlPacket *dup() const override {return new FSRControlPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual FSRControlPacketType getPacketType() const;
    virtual void setPacketType(FSRControlPacketType packetType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FSRControlPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FSRControlPacket& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/routing/fsr/FSR.msg:19 by opp_msgtool.
 */
struct INET_API FSRRoute
{
    FSRRoute();
    int source = 0;
    int target = 0;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const FSRRoute& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, FSRRoute& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FSRRoute& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FSRRoute& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/routing/fsr/FSR.msg:25</tt> by opp_msgtool.
 * <pre>
 * class FSRUpdatePacket extends FSRControlPacket
 * {
 *     FSRRoute routes[];
 * }
 * </pre>
 */
class INET_API FSRUpdatePacket : public ::inet::FSRControlPacket
{
  protected:
    FSRRoute *routes = nullptr;
    size_t routes_arraysize = 0;

  private:
    void copy(const FSRUpdatePacket& other);

  protected:
    bool operator==(const FSRUpdatePacket&) = delete;

  public:
    FSRUpdatePacket();
    FSRUpdatePacket(const FSRUpdatePacket& other);
    virtual ~FSRUpdatePacket();
    FSRUpdatePacket& operator=(const FSRUpdatePacket& other);
    virtual FSRUpdatePacket *dup() const override {return new FSRUpdatePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setRoutesArraySize(size_t size);
    virtual size_t getRoutesArraySize() const;
    virtual const FSRRoute& getRoutes(size_t k) const;
    virtual FSRRoute& getRoutesForUpdate(size_t k) { handleChange();return const_cast<FSRRoute&>(const_cast<FSRUpdatePacket*>(this)->getRoutes(k));}
    virtual void setRoutes(size_t k, const FSRRoute& routes);
    virtual void insertRoutes(size_t k, const FSRRoute& routes);
    [[deprecated]] void insertRoutes(const FSRRoute& routes) {appendRoutes(routes);}
    virtual void appendRoutes(const FSRRoute& routes);
    virtual void eraseRoutes(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FSRUpdatePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FSRUpdatePacket& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::FSRControlPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::FSRControlPacket*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::FSRRoute *p) {return any_ptr(p);}
template<> inline inet::FSRRoute *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::FSRRoute>(); }
template<> inline inet::FSRUpdatePacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::FSRUpdatePacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_FSR_M_H

